#
# Source code address
# https://hub.docker.com/u/tranhuucuong91/
#
# syntax: https://docs.docker.com/compose/yml/
#
web_service:
    #image: tranhuucuong91/php-for-wordpress:0.1
    build: .
    links:
        - mysql:mysql
    ports:
        - "80:80"
    #volumes:
    #    - /var/www/project3:/var/www/html
    hostname: wordpress
    domainname: coclab.lan
    #command: chmod 777 /var/www/project3 -R
    #command: sudo php5enmod mcrypt
    #command: sudo service apache2 restart
    cpu_shares: 512             # 0.5 CPU
    mem_limit: 536870912        # 512 MB RAM
    # privileged: true
    restart: always
    # stdin_open: true
    # tty: true

mysql:
    image: mysql:5.7
    volumes:
        - ./mysql_data/:/var/lib/mysql/
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_USER=it4421
        - MYSQL_PASSWORD=12345678
        - MYSQL_DATABASE=it4421
    ports:
        - "3308:3306"
    hostname: mysql
    domainname: coclab.lan
    cpu_shares: 512             # 0.5 CPU
    mem_limit: 11536870912        # 512 MB RAM
    # privileged: true
    restart: always
    # stdin_open: true
    # tty: true

